export const USER_PACKAGES_REQUEST = "USER_PACKAGES_REQUEST";
export const USER_PACKAGES_SUCCESS = "USER_PACKAGES_SUCCESS";
export const USER_PACKAGES_FAIL = "USER_PACKAGES_FAIL";
export const USER_RIDES_REQUEST = "USER_RIDES_REQUEST";
export const USER_RIDES_SUCCESS = "USER_RIDES_SUCCESS";
export const USER_RIDES_FAIL = "USER_RIDES_FAIL";
export const USER_TESTIMONIALS_REQUEST = "USER_TESTIMONIALS_REQUEST";
export const USER_TESTIMONIALS_SUCCESS = "USER_TESTIMONIALS_SUCCESS";
export const USER_TESTIMONIALS_FAIL = "USER_TESTIMONIALS_FAIL";
export const USER_GALLERY_REQUEST = "USER_GALLERY_REQUEST";
export const USER_GALLERY_SUCCESS = "USER_GALLERY_SUCCESS";
export const USER_GALLERY_FAIL = "USER_GALLERY_FAIL";
export const USER_ROOMS_REQUEST = "USER_ROOMS_REQUEST";
export const USER_ROOMS_SUCCESS = "USER_ROOMS_SUCCESS";
export const USER_ROOMS_FAIL = "USER_ROOMS_FAIL";
export const USER_ADDONS_REQUEST = "USER_ADDONS_REQUEST";
export const USER_ADDONS_SUCCESS = "USER_ADDONS_SUCCESS";
export const USER_ADDONS_FAIL = "USER_ADDONS_FAIL";
export const USER_TICKETS_REQUEST = "USER_TICKETS_REQUEST";
export const USER_TICKETS_SUCCESS = "USER_TICKETS_SUCCESS";
export const USER_TICKETS_FAIL = "USER_TICKETS_FAIL";
export const USER_ROOMS_LIST_REQUEST = "USER_ROOMS_LIST_REQUEST";
export const USER_ROOMS_LIST_SUCCESS = "USER_ROOMS_LIST_SUCCESS";
export const USER_ROOMS_LIST_FAIL = "USER_ROOMS_LIST_FAIL";
export const USER_PACKAGES_LIST_REQUEST = "USER_PACKAGES_LIST_REQUEST";
export const USER_PACKAGES_LIST_SUCCESS = "USER_PACKAGES_LIST_SUCCESS";
export const USER_PACKAGES_LIST_FAIL = "USER_PACKAGES_LIST_FAIL";

// Booking summary (water park)
export const USER_BOOKING_SUMMARY_REQUEST = "USER_BOOKING_SUMMARY_REQUEST";
export const USER_BOOKING_SUMMARY_SUCCESS = "USER_BOOKING_SUMMARY_SUCCESS";
export const USER_BOOKING_SUMMARY_FAIL = "USER_BOOKING_SUMMARY_FAIL";

export const USER_BOOKING_CREATE_REQUEST = "USER_BOOKING_CREATE_REQUEST";
export const USER_BOOKING_CREATE_SUCCESS = "USER_BOOKING_CREATE_SUCCESS";
export const USER_BOOKING_CREATE_FAIL = "USER_BOOKING_CREATE_FAIL";

export const USER_PAYMENT_ORDER_REQUEST = "USER_PAYMENT_ORDER_REQUEST";
export const USER_PAYMENT_ORDER_SUCCESS = "USER_PAYMENT_ORDER_SUCCESS";
export const USER_PAYMENT_ORDER_FAIL = "USER_PAYMENT_ORDER_FAIL";

export const USER_PAYMENT_CAPTURE_REQUEST = "USER_PAYMENT_CAPTURE_REQUEST";
export const USER_PAYMENT_CAPTURE_SUCCESS = "USER_PAYMENT_CAPTURE_SUCCESS";
export const USER_PAYMENT_CAPTURE_FAIL = "USER_PAYMENT_CAPTURE_FAIL";

// my bookings
export const USER_MY_BOOKINGS_REQUEST = "USER_MY_BOOKINGS_REQUEST";
export const USER_MY_BOOKINGS_SUCCESS = "USER_MY_BOOKINGS_SUCCESS";
export const USER_MY_BOOKINGS_FAIL = "USER_MY_BOOKINGS_FAIL";

// contact info
export const USER_CONTACT_REQUEST = "USER_CONTACT_REQUEST";
export const USER_CONTACT_SUCCESS = "USER_CONTACT_SUCCESS";
export const USER_CONTACT_FAIL = "USER_CONTACT_FAIL";
export const USER_CONTACT_SEND_REQUEST = "USER_CONTACT_SEND_REQUEST";
export const USER_CONTACT_SEND_SUCCESS = "USER_CONTACT_SEND_SUCCESS";
export const USER_CONTACT_SEND_FAIL = "USER_CONTACT_SEND_FAIL";

// privacy policy
export const USER_PRIVACY_REQUEST = "USER_PRIVACY_REQUEST";
export const USER_PRIVACY_SUCCESS = "USER_PRIVACY_SUCCESS";
export const USER_PRIVACY_FAIL = "USER_PRIVACY_FAIL";

// terms nad conditions
export const USER_TERMS_REQUEST = "USER_TERMS_REQUEST";
export const USER_TERMS_SUCCESS = "USER_TERMS_SUCCESS";
export const USER_TERMS_FAIL = "USER_TERMS_FAIL";


// ─── Fetch Profile ───────────────────────────────────────────
// export const PROFILE_FETCH_REQUEST = "PROFILE_FETCH_REQUEST";
// export const PROFILE_FETCH_SUCCESS = "PROFILE_FETCH_SUCCESS";
// export const PROFILE_FETCH_FAIL    = "PROFILE_FETCH_FAIL";

// ─── Update Profile (PUT / PATCH) ────────────────────────────
// export const PROFILE_UPDATE_REQUEST = "PROFILE_UPDATE_REQUEST";
// export const PROFILE_UPDATE_SUCCESS = "PROFILE_UPDATE_SUCCESS";
// export const PROFILE_UPDATE_FAIL    = "PROFILE_UPDATE_FAIL";
// export const PROFILE_UPDATE_RESET   = "PROFILE_UPDATE_RESET";
// export const USER_WPR_SECTIONS_REQUEST = "USER_WPR_SECTIONS_REQUEST";
// export const USER_WPR_SECTIONS_SUCCESS = "USER_WPR_SECTIONS_SUCCESS";
// export const USER_WPR_SECTIONS_FAIL = "USER_WPR_SECTIONS_FAIL";
// export const USER_AMENITIES_REQUEST = "USER_AMENITIES_REQUEST";
// export const USER_AMENITIES_SUCCESS = "USER_AMENITIES_SUCCESS";
// export const USER_AMENITIES_FAIL = "USER_AMENITIES_FAIL";


// ─── Fetch Profile ───────────────────────────────────────────
export const PROFILE_FETCH_REQUEST = "PROFILE_FETCH_REQUEST";
export const PROFILE_FETCH_SUCCESS = "PROFILE_FETCH_SUCCESS";
export const PROFILE_FETCH_FAIL    = "PROFILE_FETCH_FAIL";

// ─── Update Profile (PUT / PATCH) ────────────────────────────
export const PROFILE_UPDATE_REQUEST = "PROFILE_UPDATE_REQUEST";
export const PROFILE_UPDATE_SUCCESS = "PROFILE_UPDATE_SUCCESS";
export const PROFILE_UPDATE_FAIL    = "PROFILE_UPDATE_FAIL";
export const PROFILE_UPDATE_RESET   = "PROFILE_UPDATE_RESET";
export const USER_WPR_SECTIONS_REQUEST = "USER_WPR_SECTIONS_REQUEST";
export const USER_WPR_SECTIONS_SUCCESS = "USER_WPR_SECTIONS_SUCCESS";
export const USER_WPR_SECTIONS_FAIL = "USER_WPR_SECTIONS_FAIL";
// export const USER_AMENITIES_REQUEST = "USER_AMENITIES_REQUEST";
// export const USER_AMENITIES_SUCCESS = "USER_AMENITIES_SUCCESS";
// export const USER_AMENITIES_FAIL = "USER_AMENITIES_FAIL";


// amenitites
export const  USER_AMENITIES_REQUEST = "USER_AMENITIES_REQUEST";
export const  USER_AMENITIES_SUCCESS = "USER_AMENITIES_SUCCESS";
export const USER_AMENITIES_FAIL = "USER_AMENITIES_FAIL";

// About Page
export const USER_ABOUT_REQUEST = "USER_ABOUT_REQUEST";
export const USER_ABOUT_SUCCESS = "USER_ABOUT_SUCCESS";
export const USER_ABOUT_FAIL = "USER_ABOUT_FAIL";

// FAQ Page
export const USER_FAQ_REQUEST = "USER_FAQ_REQUEST";
export const USER_FAQ_SUCCESS = "USER_FAQ_SUCCESS";
export const USER_FAQ_FAIL = "USER_FAQ_FAIL";

// Hall / Auditorium
export const USER_HALL_REQUEST = "USER_HALL_REQUEST";
export const USER_HALL_SUCCESS = "USER_HALL_SUCCESS";
export const USER_HALL_FAIL = "USER_HALL_FAIL";

// Testimonial Create/Update
export const USER_TESTIMONIAL_CREATE_REQUEST = "USER_TESTIMONIAL_CREATE_REQUEST";
export const USER_TESTIMONIAL_CREATE_SUCCESS = "USER_TESTIMONIAL_CREATE_SUCCESS";
export const USER_TESTIMONIAL_CREATE_FAIL = "USER_TESTIMONIAL_CREATE_FAIL";

export const USER_TESTIMONIAL_UPDATE_REQUEST = "USER_TESTIMONIAL_UPDATE_REQUEST";
export const USER_TESTIMONIAL_UPDATE_SUCCESS = "USER_TESTIMONIAL_UPDATE_SUCCESS";
export const USER_TESTIMONIAL_UPDATE_FAIL = "USER_TESTIMONIAL_UPDATE_FAIL";
